### ISSUE TITLE
Update website with Fare media

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs.org#114]
As a result of https://github.com/google/transit/pull/355

I believe [Reference.md](https://github.com/MobilityData/gtfs.org/blob/main/docs/schedule/reference.md) will be updated automatically, but we need to manually update:
- the revision history ([CHANGES.md](https://github.com/google/transit/blob/master/gtfs/CHANGES.md) on google/transit, [process.md](https://github.com/MobilityData/gtfs.org/blob/main/docs/schedule/process.md) on ours)
- this page: https://github.com/MobilityData/gtfs.org/blob/main/docs/schedule/changes/index.md

**Comment by emmambd** [comment]
I'll make these changes today! Thanks for flagging. Reference.md will be changed within 24 hours of the merge.
