### ISSUE TITLE
Add Pathways & levels schema

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs.org#120]
## **Content request**

A pathway visual for the GTFS Pathways example section of gtfs.org. 
I still have the source of this schema, happy to modify it to better fit the style of the platform if needed. 

![pathway design](https://user-images.githubusercontent.com/63653518/229112679-2246a0a3-62a7-4d0a-8a28-d5240cbfbd30.jpg)

**Comment by emmambd** [comment]
@isabelle-dr Thanks for adding this! Two things before I can add it: 

1) There's a typo in the heading of the first diagram - "Stop locations with pathways - possible relashionships". Should be `relationships` 
2) Are you suggesting putting this at the top of the page? Or did you want to annotate a certain example with it?

**Comment by isabelle-dr** [comment]
Hello, here is an updated image without the typo. 
The top of the page seems reasonable :)

![High Quality Data brainstorm board - Pathways and levels graph](https://user-images.githubusercontent.com/63653518/235952346-1b003744-6d8a-4d66-982f-fafe8920c759.jpg)
