### ISSUE TITLE
typo in https://gtfs.org/reference/static

### ISSUE THREAD

**Issue by flocsy** [MobilityData/gtfs.org#15]
in https://gtfs.org/reference/static/#fare_rulestxt you have:

Example: If fare class "c" is associated with all travel on the GRT route that passes through zones 5, 6, and 7 the fare_rules.txt would contain these records: 
zone_id,route_id,...,contains_id

However instead of zone_id it should be fare_id

**Comment by giocorti** [comment]
Thanks catching that! The content on gtfs.org/reference/static represent the official spec and is pulled from the google/transit repository, so the fix will need to be made over there. I'm going to close this issue and work on getting the error fixed on google/transit.
