### ISSUE TITLE
Spanish website not working

### ISSUE THREAD

**Issue by bgo-eiu** [MobilityData/gtfs.org#19]
When selecting Spanish from the globe symbol language dropdown, the page redirects to what looks like a 404 on an older iteration of the English language website

**Comment by sccmcca** [comment]
@bgo-eiu 

GTFS.org under went some changes. Please clear your browser's cache to see the updates. Translations of the GTFS Schedule and Realtime references and best practices into Spanish are coming soon. In the meantime, [Google](https://developers.google.com/transit/gtfs/reference) has a version of the specification in Spanish you can consult.
