### ISSUE TITLE
Missing translation button

### ISSUE THREAD

**Issue by fernandascovino** [MobilityData/gtfs.org#193]
## **Bug report**

**Describe the bug**
The translation button doesn't show anymore on the page. Is it still available?

**Screenshots:** 
<img width="1440" alt="image" src="https://github.com/MobilityData/gtfs.org/assets/20743819/ef611f7f-a0b8-4b51-9703-56a8603bb60f">
**Environment** 

- Browser version: Brave v1.58.135 
- OS version: Mac OS

**Comment by fredericsimard** [comment]
Thank you @fernandascovino for reporting this. We are aware and investigating this, and hope for a quick fix!

**Comment by fredericsimard** [comment]
@fernandascovino The button is back, along with many small improvements. You may need to force reload the pages or empty the cache in your browser. Thank you again for reporting this!
