### ISSUE TITLE
Translation Backlog

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs.org#234]
**Last edited: on Mar 8 by @isabelle-dr   .**

This is a list of pages where the content from the translated pages doesn't match the English one. 
Before merging a PR, please add it to this list to it stays up-to-date at all times.

Date added|  Website Section  |  PR Link | Status |
|---|---|---| ---|
|Nov 19| Full resources section | N/A  | |
|Nov 19| Extensions page |  N/A |  |
|Nov 19| Extensions / Flex | N/ A | |
|Nov 19| Extensions / Fares v2 change | #158||
|Nov 19| Extensions / Fares v2 change | #170 ||
|Nov 19| Schedule / REFERENCE.md: Timeframes | #171||
|Nov 19| Schedule / REFERENCE.md: shape_dist_traveled| #174||
|Nov 19| Schedule / Examples: Fares v2| #175||
|Nov 19| Schedule / REFERENCE.md: Recommended presence| #176 | |
|Nov 19| Extensions / Fares v2: Add PVTA and MBTA | #177 | |
|Nov 19| Schedule / Examples: Fares v2 - fare_media=1 | #178 ||
|Nov 19| Schedule / REFERENCE.md: Fares v2 - fare_media=1 | #179 ||
|Nov 19| Schedule / Extensions: Fares v2- Image fix | #180 ||
|Nov 19| Schedule / Examples: Fares v2 modifications | #182 ||
|Nov 19| Schedule / Examples: timeframes empty values fix | #183 ||
|Nov 19| GTFS Schedule / Best Practices: Remove duplicate direction in best practices| #188 ||
|Nov 19| GTFS Schedule index changes (homepage changes here have been translated) | #138 ||
|Nov 20| Schedue / Validate: Update version number on the Validate page | #230 ||
|Nov 20| All - remove "edit this page" | #237 ||
|Nov 29|Add networks changes to Fares v2 page |#244|
|Nov 30| Networks modifications: Fares v2| #245 ||
|Dec 08| Update to home page| #246 ||
|Dec 15| Update fares v2 data examples| #247 ||
|Dec 20| Fix broken link and add data examples on landing Schedule page| #252 ||
|Dec 20| Schedule / index.md: Getting Help & Community | #256  | |
|Dec 22| Update Pathways.md | #248  | |
|Dec 22| Add Data Playbook | #219  | |
|Jan 3| Best practices and minor GTFS Static spec editorial fix | #272 ||
|Jan 3| Fares network modifications | #243 ||
|Jan 5| Best practices removal and fares network edits| #274 ||
|Jan 6| Update Revision History| #233 ||
|Jan 6| Small fixes to the pathways page| #260 ||
|Jan 15| Add Fares v2 resources and intro video| #277 ||
|Jan 15| Add Publishing section| #276 ||
|Jan 15| Minor updates to pathways page| #278 ||
|Jan 15| Fix broken link (button) in Schedule landing page| #280 ||
|Jan 15| Fix rendering on Recently Merged Proposals| #279 ||
|Feb 14| Automated content update on Resource section| #281 ||
|Feb 14| Amend Best Practice documentation| #341 ||
|Feb 22| Automated content update on Resource section| #353 ||
|Mar 8| Automated content update on Resource section, GTFS Schedule and Realtime Best Practices| #374 ||
|Mar 8| Minor changes to Pathway data example| #370 ||

**Comment by isabelle-dr** [comment]
Closing, we are going to re-do all translations from scratch as part of the new release
