### ISSUE TITLE
The +1 and -1 page specific feedback isn't working anymore

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs.org#27]
The feedback don't seem to be working anymore, I don't see them anymore
<img width="1433" alt="Screen Shot 2022-08-05 at 10 29 53 AM" src="https://user-images.githubusercontent.com/63653518/183098505-0aaddcde-d6c1-4e8a-81fb-28dcdfebff06.png">

**Comment by sccmcca** [comment]
I updated mkdocs-material-insiders. It should be fixed now. LMK if LGTY!

**Comment by isabelle-dr** [comment]
Solved! Thank you Scott. 

<img width="142" alt="Screen Shot 2022-08-08 at 1 23 39 PM" src="https://user-images.githubusercontent.com/63653518/183476826-95165883-bb65-4567-835c-762e3d3f759b.png">
