### ISSUE TITLE
Proposal: add a validation page on gtfs.org

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs.org#29]
## Context
In the attempt to make the Canonical GTFS Schedule Validator more accessible to small transit agencies, we recently created, with the help of the open source community, a validator Desktop app. and an interface for displaying the results.
Although this improves by a lot the accessibility of this free tool, the path to download the app itself is still complicated for users with mid to low tech-literacy skills: 
- go to the GitHub repo
- navigate to the release page
- download the correct link in the "artefacts" section

## Proposed solution
gtfs.org is already widely used for accessing GTFS information. We would like to implement a section for validation in gtfs.org. 
This section would contain direct download links to the Desktop app (which we will update every time there is a release), a "how-to", and possibly some type of rendering of the validation rules documentation. The goal is to provide an easier GitHub-free experience for small transit agencies.

## Key outcomes
- Small transit agencies can do the following tasks without going to GitHub, directly on gtfs.org:
  - read basic instructions on how to use the validator desktop app
  - read about what validation rules are included
  - download the app

## Out of scope
An on-demand validation service where a user could drag-drop a dataset to validate it.

## Alternatives
Host this validation page somewhere else than gtfs.org. 
Since gtfs.org is already seen as the canonical place to get information about the specification, having a section dedicated for the canonical validator seems to fit with the natural evolution of this website. The Canonical GTFS Schedule Validator is free, open source and driven by the community, this makes sense to provide this resource alongside the official specification.

**Comment by derhuerst** [comment]
> This section would contain direct download links to the Desktop app (which we will update every time there is a release) [...].

FYI There are also URLs for downloads of the *latest* release. As long as the naming of each platform's download stays stable, the links won't have to be changed.

**Comment by isabelle-dr** [comment]
@scmcca [here](https://docs.google.com/document/d/1vdqTQVCX0lS80bY_wzB3Slx7UbK5XlhKLIUOaNCbq1Q/edit#heading=h.ftphsbxu8uu8) is a first draft for the content.
After giving it some thought, I don't think we should add the information included in [RULES.md](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md) since we are planning to integrate this information in the validation report interface.

**Comment by isabelle-dr** [comment]
> FYI There are also URLs for downloads of the latest release. 


@derhuerst this is such a great recommendation, how can we do that? Do you know of a how-to document somewhere on how this could be done?

**Comment by derhuerst** [comment]
I maintain a script that downloads from a specific release:
 https://github.com/eugeneware/ffmpeg-static/blob/4.4.1/install.js#L166

But AFAIR you can just put `latest` and it will resolve to the latest non-draft release's assets. In a browser environment, that should be enough, you wouldn't have to do the S3 URL handling IIRC.
