### ISSUE TITLE
Content: Add the GTFS books by Quentin Zervaas on gtfs.org

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs.org#30]
The two GTFS and GTFS Realtime books by Quentin Zervaas have been donated to MobilityData and are available on the repository [here](https://github.com/MobilityData/GTFS-books).

This resource could be added to the [awesome-transit list](https://github.com/CUTR-at-USF/awesome-transit) (rendered on gtfs.org under [Resources](https://gtfs.org/resources/)), or the content of the book could be displayed on the website. 

To consider if we want to display it directly on the website: this book has been written in 2014, and it doesn't contain the latest information about the specification.

**Comment by sccmcca** [comment]
GTFS books has been added to the awesome transit list [here](https://github.com/CUTR-at-USF/awesome-transit/pull/216). The changes will be reflected on gtfs.org. Thanks!
