### ISSUE TITLE
Formatting button issues in gtfs.staging.org

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs.org#497]
## **Feature request**

**Is your feature request related to a problem? Please describe.**
In order to unblock #493, some formatting issues with the buttons on gtfs.staging.org need to be adjusted.

cc @eliasmbd @Sergiodero

**Comment by eliasmbd** [comment]
Here are the issues that need the formatting to be corrrected: 

Buttons are not showing up as in the designer figma. i.e.: 
<img width="1223" alt="Screenshot 2024-06-20 at 3 29 22 PM" src="https://github.com/MobilityData/gtfs.org/assets/130911698/cff96026-a9c2-4c6b-91f0-844bbb12efb1">

This happens on the following pages: 
https://staging.gtfs.org/getting_started/why_use_GTFS/
https://staging.gtfs.org/community/extensions/fares-v2/
https://staging.gtfs.org/community/extensions/flex/

The buttons on the cookie consent screen need to be revised: 
<img width="1359" alt="Screenshot 2024-06-20 at 3 32 13 PM" src="https://github.com/MobilityData/gtfs.org/assets/130911698/d2bb0cb2-2121-43df-a7d5-4215eb1d701c">

Also, buttons using external links show up misaligned: 
![image](https://github.com/MobilityData/gtfs.org/assets/130911698/4877302b-70e2-4849-a4fa-0a8fc152d0b5)

See these 2 pages: 
https://staging.gtfs.org/community/extensions/fares-v2/
https://staging.gtfs.org/community/extensions/flex/

**Comment by Sergiodero** [comment]
Thanks for this! before starting to work on this it might be good to wait for [PR 84](https://github.com/MobilityData/elrond.gtfs.org/pull/84/) (file restructure) to be merged. I've just approved the changes, but I'll let @fredericsimard move forward with the merge in case anything needs to be fixed. Thanks again everyone.

**Comment by emmambd** [comment]
Would be good to approve PR 84 ASAP then, since @Alessandro100 only has guaranteed time for this today and tomorrow. cc @fredericsimard

**Comment by Sergiodero** [comment]
I think I'll merge it to unblock Alessandro and let @fredericsimard step in in case there's any problem.
