### ISSUE TITLE
New R Package: GTFSwizard for GTFS Data Exploration and Manipulation

### ISSUE THREAD

**Issue by nelsonquesado** [MobilityData/gtfs.org#549]
## **Content request**

I'm writing to inform you about a new R package I've developed called GTFSwizard. This package is designed to simplify the exploration and manipulation of GTFS (General Transit Feed Specification) data. It provides a user-friendly interface for common tasks such as:

Data loading: Easily import GTFS data from various sources.
Data cleaning: Identify and handle common data quality issues.
Data exploration: Visualize and summarize key aspects of the GTFS feed.
Data manipulation: Create custom subsets and transformations of the data.
I believe that GTFSwizard could be a valuable tool for researchers, data analysts, and developers working with GTFS data. The package is now available on CRAN.

I would be grateful if you could consider adding a link to GTFSwizard on the GTFS.org website, possibly under a section for related tools or resources.

Thank you for your time and consideration.

**Comment by eliasmbd** [comment]
Hello @nelsonquesado! Welcome to the GTFS.org Repo. We would love to include your tool in the [Awesome Transit List](https://github.com/MobilityData/awesome-transit). Take a look at the list and submit an add request there. The list is then posted in the GTFS.org resources section.

**Comment by nelsonquesado** [comment]
@eliasmbd thank you very much. i have submited a pull request. thanks!
