### ISSUE TITLE
Add https://github.com/UTEL-UIUC/gtfs_segments to the resources section

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs.org#55]
## **Content request**

**Is your content request related to editing existing documentation?**
We've received a request to add the https://github.com/UTEL-UIUC/gtfs_segments package to the GTFS Libraries -> Python resources section of gtfs.org. 

**Additional context**
Add any other context or screenshots about the content request that can help us better understand your needs.

**Comment by isabelle-dr** [comment]
This will have to be added through the [awesome-transit-list](https://github.com/CUTR-at-USF/awesome-transit), this is where gtfs.org pulls the Resources list 😊

**Comment by emmambd** [comment]
Added issue to awesome-transit-list: https://github.com/CUTR-at-USF/awesome-transit/issues/218
