### ISSUE TITLE
route_short_name is displayed as routeshortname

### ISSUE THREAD

**Issue by tengl** [MobilityData/gtfs.org#6]
For a second I thought we have a lot of issues in our code, until I realized you have some markdown parser (or similar) that think `route_short_name` should be `routeshortname`, i.e. route _short_ name" (without the spaces).

http://gtfs.org/reference#routestxt

**Comment by antrim** [comment]
@tengl  Thank you for pointing that out. We only just updated the site and will get that fixed.

**Comment by wh0pper** [comment]
Thanks @tengl ! Just pushed the fix to this.
