### ISSUE TITLE
Please revert to old layout

### ISSUE THREAD

**Issue by keyan** [MobilityData/gtfs.org#7]
Hello!

First off, thanks for this great resource!

Noticed the layout of gtfs.org was changed very recently. I found the prior UI to be much more aesthetically pleasing, any possibility of reverting back?

**Comment by antrim** [comment]
We are still working on the new design.

**Comment by keyan** [comment]
Fair enough, thanks for the update. Looking forward to changes.

Thanks again for all your work maintaining this reference!
