### ISSUE TITLE
Make it easier to find important updates and documents on Fares v2 progress

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs.org#96]
## **Feature request**
 
We've consistently heard that it's difficult to keep track of what's going on with the GTFS community, find the right documents, and get high level updates.

**Solution**
A page on gtfs.org that has quick links to key proposals, access to the meeting calendar and notes, and an overview of the aims of Fares v2 as an extension. 

**Call for feedback**

[Current version live on gtfs.org here.](https://gtfs.org/extensions/fares-v2/)

We want to know:

- Can you skim this page for what you need when looking for updates on fares extension progress?
- Does this page include all documents and links contributors regularly refer to?
- Are there additional improvements you’d like to see?

**Comment by isabelle-dr** [comment]
I think we can close this, right? :)

**Comment by emmambd** [comment]
@isabelle-dr It's where I directed the community to during the Fares meeting and in the newsletter, so I'll leave it open for another 2 weeks before closing.
